---
  name: Fetch latest beer tap data
  on:
    workflow_dispatch:
    schedule:
      - cron: "0 10 * * *"  # 2AM PST
  
  jobs:
    scheduled:
      runs-on: ubuntu-latest
      steps:
        - name: Fetches repo
          uses: actions/checkout@v4
  
        - name: Set up Python 3.x
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'
  
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytz
  
        - name: Get and format api
          run: |-
            # Fetch the latest data and save it as JSON
            curl https://live-menu.staugustinesvancouver.com/taps.json | jq 'sort_by(.brewer, .name)' > staugustines_beers_v1.json

            cat staugustines_beers_v1.json | jq -r '
              (sort_by(.brewer, .name) | .[0] | keys_unsorted) as $keys |
              $keys, (sort_by(.brewer, .name)[] | [.[$keys[]]])
            | @csv' > staugustines_beers_v1.csv
  
        - name: Append to yearly files
          run: python3 scripts/yearly_files.py staugustines_beers_v1.json staugustines_beer_rotation_2025.json staugustines_beer_rotation_2025.csv
  
        - name: Add results to repo
          run: |-
            git config user.name "St. Augustine's Beer Ingestor"
            git config user.email "actions@users.noreply.github.com"
            git add -A *.json *.csv
            timestamp=$(date -u -Is)
            git commit -m "Update data for beer taps" || exit 0
            git push